apiVersion: v1
kind: Service
metadata:
  name: addition
  labels:
    app: cloud-engineer-challenge
spec:
  selector:
    app: addition
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: addition
  labels:
    app: cloud-engineer-challenge
spec:   # configuration of deployment
  replicas: 1
  selector:   # if there are more replicas u can manage them using selector by this deployment
    matchLabels:
      app: addition
  template:
    metadata:
      labels:
        app: addition
    spec:  # how this pod specification
      containers:
        - name: addition
          imagePullPolicy: Always
          image: thisisadam1123/devops-assignment-ajaber1-addition:latest
          ports:
            - containerPort: 80

