apiVersion: v1
kind: Service
metadata:
  name: client
  labels:
    app: cloud-engineer-challenge
spec:
  selector:
    app: client
  type: NodePort
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: client
  labels:
    app: cloud-engineer-challenge
spec:
  replicas: 1
  selector:
    matchLabels:
      app: client
  template:
    metadata:
      labels:
        app: client
    spec:
      containers:
        - name: client
          imagePullPolicy: Always
          image: thisisadam1123/devops-assignment-ajaber1-client:latest
          ports:
          - containerPort: 80


