apiVersion: v1
kind: Service
metadata:
  name: multiplication
  labels:
    app: cloud-engineer-challenge
spec:
  selector:
    app: multiplication
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: multiplication
  labels:
    app: cloud-engineer-challenge
spec:
  replicas: 1
  selector:
    matchLabels:
      app: multiplication
  template:
    metadata:
      labels:
        app: multiplication
    spec:
      containers:
        - name: multiplication
          imagePullPolicy: Always
          image: thisisadam1123/devops-assignment-ajaber1-multiplication:latest
          ports:
            - containerPort: 80

