
apiVersion: v1
kind: Service
metadata:
  name: subtraction
  labels:
    app: cloud-engineer-challenge
spec:
  selector:
    app: subtraction
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: subtraction
  labels:
    app: cloud-engineer-challenge
spec:
  replicas: 1
  selector:
    matchLabels:
      app: subtraction
  template:
    metadata:
      labels:
        app: subtraction
    spec:
      containers:
        - name: subtraction
          imagePullPolicy: Always
          image: thisisadam1123/devops-assignment-ajaber1-subtraction:latest
          ports:
            - containerPort: 80





