version: "3.7"
services:
  calculator:
    container_name: calculator
    labels:
      app: cloud-engineer-challenge
    # build:
    #   context: services/calculator
    #   dockerfile: Dockerfile
    image: thisisadam1123/devops-assignment-ajaber1-calculator:latest
    ports:
      - 3000:80
    links:
      - addition
      - division
      - multiplication
      - remainder
      - subtraction

  addition:
    container_name: addition
    labels:
      app: cloud-engineer-challenge
    # build:
    #   context: services/addition
    #   dockerfile: Dockerfile
    image: thisisadam1123/devops-assignment-ajaber1-addition:latest
    ports:
      - 3001:80

  division:
    container_name: division
    labels:
      app: cloud-engineer-challenge
    # build:
    #   context: services/division
    #   dockerfile: Dockerfile
    image: thisisadam1123/devops-assignment-ajaber1-division:1.0
    ports:
      - 3002:80

  multiplication:
    container_name: multiplication
    labels:
      app: cloud-engineer-challenge
    # build:
    #   context: services/multiplication
    #   dockerfile: Dockerfile
    image: thisisadam1123/devops-assignment-ajaber1-multiplication:1.0
    ports:
      - 3005:80

  remainder:
    container_name: remainder
    labels:
      app: cloud-engineer-challenge
    # build:
    #   context: services/remainder
    #   dockerfile: Dockerfile
    image: thisisadam1123/devops-assignment-ajaber1-remainder:1.0
    ports:
      - 3007:80

  subtraction:
    container_name: subtraction
    labels:
      app: cloud-engineer-challenge
    # build:
    #   context: services/subtraction
    #   dockerfile: Dockerfile
    image: thisisadam1123/devops-assignment-ajaber1-subtraction:1.0
    ports:
      - 3008:80

  client:
    container_name: client
    labels:
      app: cloud-engineer-challenge
    # build:
    #   context: services/client
    #   dockerfile: Dockerfile
    image: thisisadam1123/devops-assignment-ajaber1-client:1.0
    links:
      - calculator

